### ISSUE TITLE
Need to fix jquery populateInfoCard() to make obj data write to DOM

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/deep-cuts#19]
Line # 52 in script.js is not working as intended

Intention is to write the value of currentArtistName to the <span> tag on lines 51-53 of index.html

**Comment by serjykalstryke** [comment]
Got the artist name and a brief blurb about them to populate the card, but we may need to try another API. Wikipedia has some issues. For Nirvana, it is pulling the religious concept, not the band. Also, some of the snippets that it returns cut off mid-sentence, for example, searching Katy Perry returns "Katheryn Elizabeth Hudson (born October 25, 1984), known professionally as Katy Perry, is an American singer, songwriter, and television judge. After singing"

Bandsintown might be a better alternative and I am looking into it now.

**Comment by serjykalstryke** [comment]
For now, I have it appending the "disambiguation" section from the musicbrainz api, which is just a little snippet.

**Comment by lucsedirae** [comment]
This issue is resolved and function is working as intended
