### ISSUE TITLE
Determine needed API's and research functionality

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/deep-cuts#2]
-Bandsintown
-GoogleMaps(or open street maps)
-YouTube
-MediaWiki
-MusicBrainz **functional**

**Comment by serjykalstryke** [comment]
https://musicbrainz.org/doc/MusicBrainz_API

**Comment by serjykalstryke** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

https://github.com/Borewit/musicbrainz-api

useful links to help with musicbrainz

**Comment by lucsedirae** [comment]
Musicbrainz API is now being called and returning data into a local object
