### ISSUE TITLE
YouTube API is hardcoded with Nirvana as a q= value, link breaks when q= value is changed

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/deep-cuts#43]
Not sure how we arrived at that particular URL for this so if you can look at this one David, that would be a huge help. Otherwise the id we do actually get from the working nirvana api query is appending to DOM now

**Comment by serjykalstryke** [comment]
we could always fake it and just use Nirvana as our example for youtube functionality /s

**Comment by lucsedirae** [comment]
YouTube api call fixed and working by @serjykalstryke
