### ISSUE TITLE
Repair undefined validation in Tour Dates page

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/deep-cuts#72]
Not sure why the if/else isn't returning the undefined else portion

**Comment by serjykalstryke** [comment]
fixed

 if (response.length < 1) {
        $(".main-content").append(
          "<br><span>Sorry, no performances currently scheduled.</span>"
        );
        $("#artist-tour-pic").empy();
      } else {

**Comment by serjykalstryke** [comment]
leaving open in case we want to refine this a little bit, but I think this is solved
